version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/mongo
    ports:
        - 27017:27017

  python3.9:
    build: .
    container_name: CoinGecko
    depends_on:
      - mongo
    ports:
      - "8887:8887"
    command: ["python", "CoinGecko.py"]

  
